'''
Bethany
this file is just the main function with parameters:
x: char for getData funtion
grS: gramSize cannot be >4
ngrS: ngramSize which is actually the ngrams/line
numL: number of lines to display

-Uses python 2.7
-Generates random unigrams, bigrams, trigrams, or quadgrams from
 the editorials found in the brown corpus.
-Requires nltk
-Other parameters that may be set are found in main().
-Some additional tokenizing could be done.
-Could be easily adapted to any other text, though it crucially depends
 on the representation generated by sents in nltk, i.e., a list of sentences,
each of which is a list of words.
'''
from grams import *

def main(grS):
    gramSize = grS        #1, 2, 3, 4
    
    sentLst = getData()
    
    lst=word_gen(sentLst)
    lst=tok_words(lst)
    grams=gram_gen(lst, gramSize)
    #print(gram_dict(grams))
    freqTable(grams)  
